function(add_google_test)
  include(GoogleTest)
  cmake_parse_arguments(add_google_test "" "FNAME;LABEL;TIMEOUT;DTIMEOUT" "DEPENDS;FILES;PROPERTIES" ${ARGN})
  set(fname ${add_google_test_FNAME})
  set(label ${add_google_test_LABEL})
  set(timeout ${add_google_test_TIMEOUT})
  set(dtimeout ${add_google_test_DTIMEOUT})
  set(properties ${add_google_test_PROPERTIES})
  if(NOT ${timeout})
    set(timeout 5)
  endif()
  set(files ${add_google_test_FILES})
  set(depends ${add_google_test_DEPENDS})
  set(name utest-${label}-${fname})
  message("Test: ${name}")
  add_executable( ${name} )
  target_sources( ${name} PRIVATE ${files}  )
  target_compile_features( ${name} PRIVATE cxx_std_14 )
  set_target_properties( ${name} PROPERTIES ${properties} )
  target_compile_options( ${name} PRIVATE "-Wall" )
  target_compile_definitions( ${name} PRIVATE -DUTEST_FNAME=${fname} )
  target_include_directories( ${name} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
  target_link_libraries( ${name} PRIVATE ${depends} external::google-test)
  gtest_discover_tests( ${name}
    TEST_PREFIX "${name}_"
    PROPERTIES LABELS "${label}"
    TIMEOUT ${timeout}
    DISCOVERY_TIMEOUT ${dtimeout} )
endfunction()
